name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: pwd
      - run: yarn install
      - run: yarn run build